name: Dotfiles CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-install:
    name: Test Install Script
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prep HOME for testing
        run: |
          # Copy everything into $HOME since the dotfiles are meant to live directly in $HOME
          rsync -a ./ $HOME/

      - name: Run shellcheck format check
        if: matrix.os == 'ubuntu-latest'
        run: |
          shellcheck $HOME/.install || true

      - name: Syntax Check Zsh
        run: |
          zsh -n $HOME/.config/zsh/.zshrc
